apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: yandex/clickhouse-server
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /var/lib/clickhouse
          name: clickhouse-storage
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
